#### 주택 매매가격 변동률

In [2]:
import pandas as pd

In [3]:
file = r'C:\Users\kdp\KDT_06\KDT\EX_PY06\KDT\Project02\2018~2022 주택매매가격변동률.xlsx'

In [4]:
# 엑셀파일 ==> DataFrame으로 저장
houseDF1 = pd.read_excel(file)
houseDF1

,행정구역별(1),2018.01,2018.02,2018.03,2018.04,2018.05,2018.06,2018.07,2018.08,2018.09,...,2022.03,2022.04,2022.05,2022.06,2022.07,2022.08,2022.09,2022.10,2022.11,2022.12
0,대구광역시,0.25,0.16,0.2,0.33,0.26,0.16,0.14,0.19,0.36,...,-0.43,-0.41,-0.5,-0.52,-0.35,-0.62,-0.74,-1.02,-1.56,-2.56

In [5]:
# 행열 전치
houseDF=houseDF1.transpose()
houseDF = houseDF.drop('행정구역별(1)')
houseDF.columns = ['변동률']
houseDF.head(5)

          변동률
2018.01  0.25
2018.02  0.16
2018.03   0.2
2018.04  0.33
2018.05  0.26

In [6]:
# 연도별로 데이터 나누기
houseDF_18 = houseDF.iloc[0:12]
houseDF_19 = houseDF.iloc[12:24]
houseDF_20 = houseDF.iloc[24:36]
houseDF_21 = houseDF.iloc[36:48]
houseDF_22 = houseDF.iloc[48:60]

In [7]:
# 데이터프레임 합치기 위해 행인덱스 통일, 열 인덱스는 연도로 나누기
month = ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월']
houseDF_18.columns=['2018년']
houseDF_18.index = month
houseDF_19.columns=['2019년']
houseDF_19.index = month
houseDF_20.columns=['2020년']
houseDF_20.index = month
houseDF_21.columns=['2021년']
houseDF_21.index = month
houseDF_22.columns=['2022년']
houseDF_22.index = month

In [8]:
# 데이터 프레임 합치기 concat() 함수 사용
sum_houseDF = pd.concat([houseDF_18,houseDF_19,houseDF_20,houseDF_21,houseDF_22],axis=1)

In [9]:
# 주택 매매가 변동률 평균 행 추가
sum_houseDF.loc['평균'] = [sum_houseDF['2018년'].mean(),sum_houseDF['2019년'].mean(),sum_houseDF['2020년'].mean(),sum_houseDF['2021년'].mean(),sum_houseDF['2022년'].mean()]
sum_houseDF

        2018년     2019년     2020년     2021년   2022년
1월       0.25      0.15      0.41      1.15   -0.22
2월       0.16      0.08      0.29       1.3   -0.28
3월        0.2      0.05      0.06      1.11   -0.43
4월       0.33      0.02     -0.12      0.82   -0.41
5월       0.26      0.06         0      0.79    -0.5
6월       0.16      0.03      0.22      0.84   -0.52
7월       0.14      0.01      0.26      0.34   -0.35
8월       0.19      0.03      0.48      0.27   -0.62
9월       0.36      0.08      0.72      0.15   -0.74
10월      0.56      0.19      0.75      0.09   -1.02
11월      0.53      0.22      1.06         0   -1.56
12월      0.44      0.29      1.59      -0.1   -2.56
평균   0.298333  0.100833  0.476667  0.563333 -0.7675